Contact form for Potfolio
yawsamcode/portfolio pull request #4
Opened 2023-02-22 23:16 UTC by yawsamcode

I updated the portfolio website with the following features; 

- Created a contact form to help my clients and potential employers reach out to me. 
- I also connected the form https://formspree.io/html to collect and save the details harvested from the form. 
- Added Social Media icons/links to the footer of the pages.

2023-02-23 00:25 UTC, ouasamine requested changes
Hi @yawsamcode  and @prius2055 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- Implement Formspree form successfully ✔️ 
- Nice work on the UI 👏🏽 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 00:25 UTC, ouasamine commented on README.md
> +- [Live Demo Link](#)
- [ ] Very good job using the provided README template, please make sure to remove this live demo section, since you haven't deployed your project yet and you don't have a working live link yet.

2023-02-23 00:25 UTC, ouasamine commented on css/styles.css
> +form li,
- [ ] Your style file is currently not loaded correctly and is not applied to your page (check the image below 🔽), please fix the link of the stylesheet in your head tag to be like this `<link rel="stylesheet" href="./css/styles.css"> ` note how I added "./" instead of just "/".

![hww](https://user-images.githubusercontent.com/104319462/220793190-7128e6fe-136c-4a8c-bc05-246ea14e50ff.png)

2023-02-23 00:25 UTC, ouasamine commented on index.html
> +            </li>
- [ ] Nice work implementing this contact form it's working fine however, please make sure that this input type is set to `type="text"` as stated in the project's [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md).

2023-02-23 00:25 UTC, ouasamine commented on css/styles.css
> +}
- [ ] Please make sure to use `display: flex;` to lay out the form elements as required by the project's [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md)

2023-02-23 00:25 UTC, ouasamine commented on index.html
> +    </ul>
- [ ] Please use the correct paths for these social media icons as they are not shown properly currently like indiated below 🔽 

![social](https://user-images.githubusercontent.com/104319462/220794116-344eb5a5-82e4-434d-b238-02058cddbc35.png)

2023-02-23 09:51 UTC, yawsamcode commented on README.md
> +- [Live Demo Link](#)
Thanks for the feedback👍. I fixed that.

2023-02-23 11:01 UTC, yawsamcode commented on css/styles.css
> +form li,
I tried to fix this. It displays perfectly when viewed in vscode with the help live server extension. I followed your advice by adding the .(dot) >> href="./css/styles.css"> . 

![Screenshot from 2023-02-23 10-51-59](https://user-images.githubusercontent.com/106739167/220886513-3602decd-d7b3-4b57-a254-8725fa4229ef.png)

I observed that when I open the index file directly with my browser the background image disappears. 
![Screenshot from 2023-02-23 11-00-20](https://user-images.githubusercontent.com/106739167/220888309-ff9298d8-52c9-4257-b1dc-32ffcd14af4b.png)

![Screenshot from 2023-02-23 10-58-08](https://user-images.githubusercontent.com/106739167/220888285-2e17ef69-f580-4725-84d0-e9f194c577aa.png)

2023-02-23 11:08 UTC, yawsamcode commented on index.html
> +            </li>
I implemented this as well. Thank you
![Screenshot from 2023-02-23 11-04-43](https://user-images.githubusercontent.com/106739167/220889753-f6e5b7ba-b940-4f3c-a005-6b4d622c6252.png)

2023-02-23 11:11 UTC, yawsamcode commented on css/styles.css
> +}
I have also implemented display: flex; in the form section. 
![Screenshot from 2023-02-23 11-03-52](https://user-images.githubusercontent.com/106739167/220889911-180548f7-ba5a-4717-81f3-c21cc4887675.png)

2023-02-23 11:13 UTC, yawsamcode commented on index.html
> +    </ul>
I have corrected the paths for the social media icons. 
![Screenshot from 2023-02-23 11-11-45](https://user-images.githubusercontent.com/106739167/220890449-5895ad79-8b90-4d0e-a86c-ad4ccc668b8d.png)

2023-02-23 11:34 UTC, Ibizugbe approved these changes
Hi @yawsamcode 👋👋, 

![ShakeAndBakeShakeNBakeGIF (2)](https://user-images.githubusercontent.com/64643995/220893813-8b8a83e5-c886-4af1-aceb-233ac92fee76.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] Your mode of communication with the reviewer is very detailed and polite, keep it up😉👍
- [x] Linters are checked👍
- [x] formspre service has been used👍
- [x] The changes requested by the previous reviewer has been implemented👍

## Optional suggestions
- [OOPTIONAL] Nice job so far😉 Let's make your project look more professional by sticking to the design😉 the position of your submit button is different from the design😉😉
<img width="275" alt="YOUR CONTACT" src="https://user-images.githubusercontent.com/64643995/220894708-48f209c9-0e8a-47ee-b503-9d142360c33c.png">

<img width="239" alt="DESIGN CONTACTTTT" src="https://user-images.githubusercontent.com/64643995/220894732-573e1037-a54b-4b05-8ee8-efd5a5af335c.png">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 11:45 UTC, merged

2023-02-28 10:37 UTC, IngDavidTM reviewed
## Hi @yawsamcode  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 10:37 UTC, IngDavidTM commented on index.html
> +    </form>
- [ ] Great job on the layout of your form section! However, I suggest placing the form elements in the center of the page to align more closely with the Figma template :+1:. As you can see, in the image below, the elements appear to be slightly left-aligned.

**Your design**

![Screenshot from 2023-02-28 05-27-27](https://user-images.githubusercontent.com/105117832/221828873-2b990c27-954e-4895-9803-5e891b371cde.png)

**Figma**

![Screenshot from 2023-02-28 05-28-26](https://user-images.githubusercontent.com/105117832/221828983-daa7b7df-33b1-4cc9-aa7e-2a152cbe88d7.png)

2023-02-28 10:37 UTC, IngDavidTM commented on index.html
> +                <button class="submit-btn" type="submit">Get in Touch</button>
- [ ] You did a great job adding hover interaction to your buttons :+1:, but to meet the project requirements, please ensure that you also implement the `pressed` interaction.

![Screenshot from 2023-02-28 05-28-49](https://user-images.githubusercontent.com/105117832/221829587-9b5fcb59-ed02-4be4-840e-7a471a33ab9f.png)