Desktop view Update
yawsamcode/portfolio pull request #9
Opened 2023-03-02 18:58 UTC by yawsamcode

I added various parts of the desktop version with a responsive layout.

2023-03-03 09:29 UTC, Shedrack-Sunday requested changes
Hi @yawsamcode    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Proper PR summary 
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required has to do with a little bit of `CSS` adjustments


_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-03 09:29 UTC, Shedrack-Sunday commented on index.html
>                  <h2 class="about-me-title">About Me</h2>
- [ ] Good job working on this feature 👏 . However, the placement of the background image in your design needs a little adjustment to tally with that of the one given on the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=I0SUZ5FGkB27z6XP-0) Template. The reason for emphasizing this Is to help you build a programming muscle in meeting the requirements as given, which is the medium clients or your manager will follow. I've made a comparison below for your review 

## Figma
![image](https://user-images.githubusercontent.com/50990925/222678987-21777260-5754-4f44-8641-d5ed5bd7add5.png)

## Your design:
![image](https://user-images.githubusercontent.com/50990925/222679839-651ea1fd-8c97-4111-b3be-afbce2954662.png)

2023-03-03 09:29 UTC, Shedrack-Sunday commented on index.html
> +                <p class="stack-style2" id="stack-margin">Ruby</p>
- [ ] Nice efforts with the card 👏 . However, I noticed two issues that you need to fix.
- First, the background image of the cards on the hover effect is meant to be white, and the button is at the button, not the top. kindly fix this 👍 
- Secondly, the first card I a reference to all other cards. I strongly suggest you implement the same features in the first point above on all cards 👍 

- [ ] The reason for asking for these changes in reference to the template, is to master the art of sticking to user requirements, and have a good we app that gives a better user experience 👍 

## Your view:
![image](https://user-images.githubusercontent.com/50990925/222681888-29b4ac55-e3c4-44f4-8830-5559c793376d.png)

## Figma guide:
![image](https://user-images.githubusercontent.com/50990925/222681989-cf6d7f11-40f3-4801-937a-7cb05d11fec8.png)

2023-03-03 09:29 UTC, Shedrack-Sunday commented on index.html
>                  <h2>I’m a software developer!</h2>
- [ ] For this section of the desktop version, kindly adjust the background image to cover up the section it occupies just as provided on the template. this gives a more visual appealing view, and heeps you keep to the rquiremnts provided 👍

## Your view:
![image](https://user-images.githubusercontent.com/50990925/222683269-717eb078-cee0-444d-8ef6-3824dca1d826.png)

## Figma:
![image](https://user-images.githubusercontent.com/50990925/222683322-b3b791fc-e4d3-45e0-9845-c93809229cb9.png)

2023-03-04 03:16 UTC, yawsamcode commented on index.html
>                  <h2 class="about-me-title">About Me</h2>
@Shedrack-Sunday Thanks for your feedback. I made effort to modify this to my best my only challenge was getting the background image to touch the border. I have set a padding round the page so I am not sure how to maneuver this at the moment. I believe if given the opportunity overtime I will figure it out. As for now time is running out 
![challenge](https://user-images.githubusercontent.com/106739167/222873173-bae657de-afbf-43ba-a953-580c9856d210.PNG)

![image](https://user-images.githubusercontent.com/106739167/222873144-136963fe-ee34-490f-8b77-
![image](https://user-images.githubusercontent.com/106739167/222873151-b9b57f56-16d1-4f97-bae1-ea4ae247a4e9.png)
1fdf2177184d.png)

2023-03-04 03:23 UTC, yawsamcode commented on index.html
> +                <p class="stack-style2" id="stack-margin">Ruby</p>
After a long battle I was able to come close to the figma design. Its was though for me but I loved the challenge. 💪👊😆👊💪
![see](https://user-images.githubusercontent.com/106739167/222873398-5a71940c-1086-4c63-92a6-75e58b9d572f.PNG)

2023-03-04 03:30 UTC, yawsamcode commented on index.html
>                  <h2>I’m a software developer!</h2>
I also tried to come up with the solution for this. After everything i feel like I just finished a boxing match. Let me go get a glass of juicer while I wait to hear from the all mighty code reviewer. Its a weekend so well all need to go get some fun. No more  coding for now.  Enjoy :) 😆😋😋😍
![Capture](https://user-images.githubusercontent.com/106739167/222873519-0b588db6-d7a5-4df5-95f2-d9e926995aa6.PNG)

2023-03-04 03:47 UTC, mahbubul14 requested changes
Hi @yawsamcode,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-04 03:47 UTC, mahbubul14 commented on index.html
>                  <h2 class="about-me-title">About Me</h2>
> * [x]  Good job working on this feature clap . However, the placement of the background image in your design needs a little adjustment to tally with that of the one given on the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=I0SUZ5FGkB27z6XP-0) Template. The reason for emphasizing this Is to help you build a programming muscle in meeting the requirements as given, which is the medium clients or your manager will follow. I've made a comparison below for your review
> 
> ## Figma
> ![image](https://user-images.githubusercontent.com/50990925/222678987-21777260-5754-4f44-8641-d5ed5bd7add5.png)
> 
> ## Your design:
> ![image](https://user-images.githubusercontent.com/50990925/222679839-651ea1fd-8c97-4111-b3be-afbce2954662.png)

- [ ] As the previous reviewer suggested, Kindly fix the issue. :+1:

2023-03-04 12:48 UTC, amejid approved these changes
Hi @yawsamcode, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 12:48 UTC, amejid commented on index.html
> +            <div class="sub-project2">
- [ ] [OPTIONAL] I highly recommend you implement the changes suggested by the first reviewer. The image on the left indicates the state of the cards on hover. So every card should show the `See project` button when hovering over them. 😎️

![image](https://user-images.githubusercontent.com/17243325/222902058-466f8898-bd07-4e21-bb88-00ab1d0ab516.png)

2023-03-04 12:52 UTC, merged